# jekyll configuration

title: "Transfuse"
pygments: true

currentVersion: "0.2.10"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

# end of configuration
