# jekyll configuration

title: "Transfuse"
pygments: true

currentVersion: "0.3.0-beta-3"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

# end of configuration
